import { tv } from 'tailwind-variants'

export const text = tv({
  base: '',
  variants: {
    variant: {
      inherit: '',
      h1: 'typography-h1',
      h2: 'typography-h2',
      h3: 'typography-h3',
      h4: 'typography-h4',
      overline: 'typography-overline',
      subtitle: 'typography-subtitle',
      displayTitle: 'typography-display-title',
      displayBody: 'typography-display-body',
      body: 'typography-body',
      bodyStrong: 'typography-body-strong',
      bodySmall: 'typography-body-small',
      bodySmallStrong: 'typography-body-small-strong',
      bodyLarge: 'typography-body-large',
      bodyLargeStrong: 'typography-body-large-strong',
      action: 'typography-action',
      actionLarge: 'typography-body-large',
      actionSmall: 'typography-body-small',
    },
    color: {
      inherit: 'text-inherit',
      'content.primary': 'text-content-primary',
      'content.primary.enabled': 'text-content-primary-enabled',
      'content.primary.hover': 'text-content-primary-hover',
      'content.primary.pressed': 'text-content-primary-pressed',
      'content.primary.focus': 'text-content-primary-focus',
      'content.primary.active': 'text-content-primary-active',
      'content.primary.disabled': 'text-content-primary-disabled',
      'content.neutral': 'text-content-neutral',
      'content.neutral.enabled': 'text-content-neutral-enabled',
      'content.neutral.hover': 'text-content-neutral-hover',
      'content.neutral.pressed': 'text-content-neutral-pressed',
      'content.neutral.focus': 'text-content-neutral-focus',
      'content.neutral.active': 'text-content-neutral-active',
      'content.neutral.disabled': 'text-content-neutral-disabled',
      'content.neutral.low': 'text-content-neutral-low',
      'content.neutral.lowest': 'text-content-neutral-lowest',
      'content.neutral.lowest.enabled':
        'text-content-neutral-lowest-enabled',
      'content.neutral.lowest.hover': 'text-content-neutral-lowest-hover',
      'content.neutral.lowest.pressed':
        'text-content-neutral-lowest-pressed',
      'content.neutral.lowest.focus': 'text-content-neutral-lowest-focus',
      'content.neutral.lowest.active': 'text-content-neutral-lowest-active',
      'content.neutral.lowest.disabled':
        'text-content-neutral-lowest-disabled',
      'content.danger': 'text-content-danger',
      'content.danger.enabled': 'text-content-danger-enabled',
      'content.danger.hover': 'text-content-danger-hover',
      'content.danger.pressed': 'text-content-danger-pressed',
      'content.danger.focus': 'text-content-danger-focus',
      'content.danger.active': 'text-content-danger-active',
      'content.danger.disabled': 'text-content-danger-disabled',
      'content.warning': 'text-content-warning',
      'content.warning.enabled': 'text-content-warning-enabled',
      'content.warning.hover': 'text-content-warning-hover',
      'content.warning.pressed': 'text-content-warning-pressed',
      'content.warning.focus': 'text-content-warning-focus',
      'content.warning.active': 'text-content-warning-active',
      'content.warning.disabled': 'text-content-warning-disabled',
      'content.success': 'text-content-success',
      'content.success.enabled': 'text-content-success-enabled',
      'content.success.hover': 'text-content-success-hover',
      'content.success.pressed': 'text-content-success-pressed',
      'content.success.focus': 'text-content-success-focus',
      'content.success.active': 'text-content-success-active',
      'content.success.disabled': 'text-content-success-disabled',
      'content.info': 'text-content-info',
      'content.info.enabled': 'text-content-info-enabled',
      'content.info.hover': 'text-content-info-hover',
      'content.info.pressed': 'text-content-info-pressed',
      'content.info.focus': 'text-content-info-focus',
      'content.info.active': 'text-content-info-active',
      'content.info.disabled': 'text-content-info-disabled',
      'content.promo': 'text-content-promo',
      'content.form.enabled': 'text-content-form',
      'content.form.hover': 'text-content-form-hover',
      'content.form.pressed': 'text-content-form-pressed',
      'content.form.focus': 'text-content-form-focus',
      'content.form.active': 'text-content-form-active',
      'content.form.disabled': 'text-content-form-disabled',
      'content.form.read-only': 'text-content-form-read-only',
      'content.form.invalid': 'text-content-form-invalid',
      'content.inverted': 'text-content-inverted',
      'content.inverted.enabled': 'text-content-inverted-enabled',
      'content.inverted.hover': 'text-content-inverted-hover',
      'content.inverted.pressed': 'text-content-inverted-pressed',
      'content.inverted.focus': 'text-content-inverted-focus',
      'content.inverted.active': 'text-content-inverted-active',
      'content.inverted.disabled': 'text-content-inverted-disabled',
    },
    isTruncated: {
      true: 'uy-block uy-truncate',
    },
    isLineClamped: {
      true: 'uy-line-clamp-[var(--uy-text-line-clamp)]',
    },
  },
  defaultVariants: {
    variant: 'body',
    isTruncated: false,
  },
})
